-- =========================================================================
-- MODULE 1: RELATIONAL DATABASE SCHEMA DEFINITION & INTEGRITY RULES
-- Description: Establishes baseline core relational structures for plant entities.
-- Tool Stack: SQL Server (T-SQL)
-- =========================================================================

-- 1. SUPPLIERS STRUCTURE
CREATE TABLE SUPPLIERS(
SUPPLIERID INT PRIMARY KEY IDENTITY(1,1),
SUPPLIERNAME NVARCHAR(50) NOT NULL
);

-- 2. CUSTOMERS STRUCTURE
CREATE TABLE  CUSTOMERS(
CUSTOMERID INT PRIMARY KEY IDENTITY(1,1),
CUSTOMERNAME NVARCHAR(100) NOT NULL
);

-- 3. RAW MATERIAL SPECS
CREATE TABLE RAWMATERIALS(
MATERIALID INT PRIMARY KEY IDENTITY(1,1),
MATERIALNAME NVARCHAR(100) NOT NULL,
MATERIALGRADE NVARCHAR(50) NULL,
CONSTRAINT UNIQUE_MATERIAL UNIQUE(MATERIALNAME,MATERIALGRADE)
);

-- 4. MACHINE ASSETS
CREATE TABLE MACHINES(
MACHINEID INT PRIMARY KEY IDENTITY(1,1),
MACHINECODE NVARCHAR(50) NOT NULL UNIQUE,
MACHINENAME NVARCHAR(50) NOT NULL,
MACHINETYPE NVARCHAR(50) NULL,
PLANTID NVARCHAR(10) NOT NULL,
LASTMAINTAINCEDATE DATE NULL
);

-- 5. PRODUCTION TRANSFERS
CREATE TABLE PRODUCTIONORDERS(
PRODUCTIONID INT PRIMARY KEY IDENTITY(1,1),
PRODUCTIONCODE NVARCHAR(20) NOT NULL UNIQUE,
CUSTOMERID INT NOT NULL,
COMPONENTTOPRODUCE NVARCHAR(200) NOT NULL,
QUANTITYTOPRODUCE INT NOT NULL,
ORDERDATE DATETIME NOT NULL,
SCHEDULEDSTARTDATE DATETIME NOT NULL,
SCHEDULEENDDATE DATETIME NOT NULL,
[STATUS] NVARCHAR (50) NOT NULL,
ASSIGNEDMACHINEID INT NOT NULL,
PLANTID NVARCHAR(3) NOT NULL,

FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID),
FOREIGN KEY (ASSIGNEDMACHINEID) REFERENCES MACHINES(MACHINEID),
CONSTRAINT CHK_PRODUCTION_STATUS CHECK( [STATUS] IN ('Scheduled','In Progress','Completed','On Hold', 
'Cancelled', 'Rework Required','Quoted','Pending Materials','Rework Complete')),

CONSTRAINT CHK_ORDERDATES CHECK (SCHEDULEDSTARTDATE>=ORDERDATE),
CONSTRAINT CHK_SCHEDULESEQUENCE CHECK (SCHEDULEENDDATE >= SCHEDULEDSTARTDATE)
);

-- 6. INVENTORY STOCKS
CREATE TABLE MATERIALINVENTORY(
BATCHID INT PRIMARY KEY IDENTITY (1,1),
ORIGINALBATCHID NVARCHAR(50) UNIQUE,
MATERIALID INT NOT NULL,
SUPPLIERID INT NOT NULL,
RECEIVED_DATE DATE NOT NULL,
INITIAL_QUANTITY DECIMAL (10,2) NOT NULL,
REMAINING_QUANTITY DECIMAL (9,2) NULL,
UNIT NVARCHAR(10) NOT NULL,

FOREIGN KEY (MATERIALID) REFERENCES RAWMATERIALS(MATERIALID),
FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIERS(SUPPLIERID),
CONSTRAINT CHK_UNIT CHECK (UNIT IN ('KG','M','PCS','FT','SQ_FT','LBS'))
);

-- 7. BILL OF MATERIALS REALIZED CONSUMPTION
CREATE TABLE PRODUCTIONMATERIALUSAGE(
USAGEID INT PRIMARY KEY IDENTITY (1,1),
PRODUCTIONORDERID INT NOT NULL,
BATCHID INT NOT NULL,
QUANTITY_USED DECIMAL(10,2) NOT NULL,

FOREIGN KEY (PRODUCTIONORDERID) REFERENCES PRODUCTIONORDERS(PRODUCTIONID),
FOREIGN KEY (BATCHID) REFERENCES MATERIALINVENTORY (BATCHID),
CONSTRAINT FK_PRODUCTION FOREIGN KEY (MATERIALID) REFERENCES RAWMATERIALS(MATERIALID)
);

-- 8. PERSONNEL SYSTEM
CREATE TABLE EMPLOYEES(
EMPLOYEEID INT PRIMARY KEY IDENTITY(1,1),
FULLNAME NVARCHAR(100) NOT NULL,
[ROLE] NVARCHAR(50) NOT NULL
);

-- 9. AUDITING CONTROL FLUIDS
CREATE TABLE QUALITYCHECKS(
QUALITYCHECKID INT PRIMARY KEY IDENTITY(1,1),
ORIGINALQUALITYCHECKID NVARCHAR(50),
PRODUCTIONORDERID INT NOT NULL,
INSPECTORID INT NOT NULL,
CHECKTIMESTAMP DATETIME NOT NULL,
RESULT NVARCHAR(10),

FOREIGN KEY (PRODUCTIONORDERID) REFERENCES PRODUCTIONORDERS(PRODUCTIONID),
FOREIGN KEY (INSPECTORID) REFERENCES EMPLOYEES(EMPLOYEEID)
);

-- 10. REAL-TIME PROCUREMENT ALERT STACK
CREATE TABLE MATERIALLOWSTOCKLOG (
LOGINID INT PRIMARY KEY IDENTITY(1,1),
MATERIALID INT NOT NULL,
MATERIALNAME NVARCHAR(100),
MATERIALGRADE NVARCHAR(50),
ALERTTRIGGERQUANTITY DECIMAL(10,2),
QUANTITYORDEER DECIMAL(10,2),
ALERTDATE DATETIME DEFAULT GETDATE()
);