-- =========================================================================
-- MODULE 3: ATOMIC DATA PRODUCTION MIGRATION RUN
-- Description: populates cleaned dimensional data tables via explicit relational mappings.
-- =========================================================================

-- 1. DIMENSIONAL MASTER TABLES POPULATION

INSERT INTO SUPPLIERS(SUPPLIERNAME)
SELECT DISTINCT SUPPLIERNAME FROM DUMMY WHERE SUPPLIERNAME IS NOT NULL;

INSERT INTO CUSTOMERS(CUSTOMERNAME)
SELECT DISTINCT CUSTOMERNAME FROM DUMMY;

INSERT INTO RAWMATERIALS(MATERIALNAME, MATERIALGRADE)
SELECT DISTINCT MATERIALNAME, MATERIALGRADE FROM ABC_10000;

-- 2. STRUCTURAL DIMENSION POPULATION WITH TYPE CONVERSION

INSERT INTO MACHINES(MACHINENAME, MACHINETYPE, PLANTID, LASTMAINTAINCEDATE)
SELECT DISTINCT 
    TRIM(REPLACE(REPLACE(MACHINENAME, 'P1-', ''), 'P2-', '')),
    TRIM(MACHINETYPE),
    LEFT(MACHINENAME, 2),
    MAX(TRY_CONVERT(DATE, LASTMAINTENANCEDATE)) 
FROM ABC_10000
GROUP BY TRIM(REPLACE(REPLACE(MACHINENAME, 'P1-', ''), 'P2-', '')), TRIM(MACHINETYPE), LEFT(MACHINENAME, 2);

-- 3. MIGRATION RUN: MATERIAL INVENTORY FACT RECORD LINKAGES

WITH CleanedInventory_CTE AS (
    SELECT 
        LEFT(RAWMATERIALBATCHID, 7) AS RAWMATERIALBATCHID,
        TRY_CONVERT(DATE, RECEIVEDATE, 105) AS RECEIVEDDATE,
        CAST(CAST(REPLACE(REPLACE(REPLACE(INITIALQUANTITY, '$', ''), ',', ''), ' ', '') AS FLOAT) AS DECIMAL(10,2)) AS INITIAL_QUANTITY,
        CASE
            WHEN UPPER(TRIM(UNIT)) IN ('KG','KILOGRAM','KGS') THEN 'KG'
            WHEN UPPER(TRIM(UNIT)) IN ('M','METERS','METER') THEN 'M'
            WHEN UPPER(TRIM(UNIT)) IN ('PCS','PIECES') THEN 'PCS'
            WHEN UPPER(TRIM(UNIT)) IN ('FT','FEET') THEN 'FT'
            WHEN UPPER(TRIM(UNIT)) IN ('SQ FT','SQUQRE FEET') THEN 'SQ_FT'
            WHEN UPPER(TRIM(UNIT)) = 'LBS' THEN 'LBS'
            ELSE NULL
        END AS STANDARDUNIT, 
        SUPPLIERNAME, MATERIALNAME, MATERIALGRADE
    FROM DUMMY
)
INSERT INTO MATERIALINVENTORY(ORIGINALBATCHID, MATERIALID, SUPPLIERID, RECEIVED_DATE, INITIAL_QUANTITY, UNIT)
SELECT 
    T.RAWMATERIALBATCHID, M.MATERIALID, S.SUPPLIERID, T.RECEIVEDDATE, T.INITIAL_QUANTITY, T.STANDARDUNIT 
FROM CleanedInventory_CTE AS T 
INNER JOIN SUPPLIERS AS S ON S.SUPPLIERNAME = T.SUPPLIERNAME
INNER JOIN RAWMATERIALS AS M ON M.MATERIALGRADE = T.MATERIALGRADE AND M.MATERIALNAME = T.MATERIALNAME;

-- 4. MIGRATION RUN: FACT PRODUCTION TRANSACTIONS
-- Cleans structural multi-format raw strings into standard Datetime variables.

INSERT INTO PRODUCTIONORDERS (
    PRODUCTIONCODE, CUSTOMERID, COMPONENTTOPRODUCE, QUANTITYTOPRODUCE, 
    ORDERDATE, SCHEDULEDSTARTDATE, SCHEDULEENDDATE, [STATUS], ASSIGNEDMACHINEID, PLANTID
)
SELECT 
    RIGHT(REPLACE(REPLACE(D.PRODUCTIONORDERID, '/', '-'), '_', '-'), 4),
    C.CUSTOMERID,
    D.COMPONENTTOPRODUCE,
    CAST(CEILING(D.QUANTITYTOPRODUCE) AS INT),
    COALESCE(TRY_CONVERT(DATETIME, ORDERDATE, 105), TRY_CONVERT(DATETIME, ORDERDATE, 110)),
    TRY_CONVERT(DATETIME, SCHEDULEDSTART, 105),
    TRY_CONVERT(DATETIME, SCHEDULEDEND, 105),
    D.STATUS,
    M.MACHINEID,
    M.PLANTID
FROM DUMMY AS D
INNER JOIN CUSTOMERS AS C ON C.CUSTOMERNAME = D.CUSTOMERNAME
INNER JOIN MACHINES AS M ON M.MACHINENAME = D.MACHINENAME AND M.MACHINETYPE = D.MACHINETYPE
WHERE TRY_CONVERT(DATETIME, SCHEDULEDEND, 105) >= TRY_CONVERT(DATETIME, SCHEDULEDSTART, 105) 
  AND TRY_CONVERT(DATETIME, SCHEDULEDSTART, 105) >= COALESCE(TRY_CONVERT(DATETIME, ORDERDATE, 105), TRY_CONVERT(DATETIME, ORDERDATE, 110));

-- 5. POPULATE COMPONENT FACT DEPENDENCIES (PRODUCTION MATERIAL USAGE)

UPDATE DUMMY 
SET PRODUCTIONORDERID = RIGHT(REPLACE(REPLACE(PRODUCTIONORDERID, '/', '-'), '_', '-'), 4),
    SCHEDULEDSTART = TRY_CONVERT(DATETIME, SCHEDULEDSTART, 105),
    SCHEDULEDEND = TRY_CONVERT(DATETIME, SCHEDULEDEND, 105),
    QUANTITYTOPRODUCE = CAST(CEILING(QuantityToProduce) AS INT);

INSERT INTO PRODUCTIONMATERIALUSAGE (PRODUCTIONORDERID, BATCHID, QUANTITY_USED, MATERIALID)
SELECT P.PRODUCTIONID, MI.BATCHID, D.QuantityUsed, MI.MATERIALID 
FROM DUMMY AS D
INNER JOIN PRODUCTIONORDERS AS P ON D.ProductionOrderID = P.PRODUCTIONCODE 
    AND D.ScheduledStart = P.SCHEDULEDSTARTDATE AND D.ScheduledEnd = P.SCHEDULEENDDATE 
    AND D.QuantityToProduce = P.QUANTITYTOPRODUCE AND D.ComponentToProduce = P.COMPONENTTOPRODUCE
INNER JOIN MATERIALINVENTORY AS MI ON MI.ORIGINALBATCHID = D.MaterialUsedBatchID;

-- 6. POPULATE SEED EMPLOYEE DIRECTORY

INSERT INTO EMPLOYEES(FULLNAME, ROLE)
VALUES 
('John Doe', 'Quality Inspector'), ('Jane Smith', 'Quality Inspector'),
('Peter Jones', 'Plant Manager'), ('Mary Williams', 'Quality Inspector'),
('David Brown', 'Operator'), ('Susan Miller', 'Quality Inspector'),
('Robert Johnson', 'Plant Manager'), ('Karen White', 'Operator'),
('Michael Lee', 'Quality Inspector'), ('Patricia Garcia', 'Operator'),
('James Rodriguez', 'Operator'), ('Linda Martinez', 'Quality Inspector'),
('Charles Hernandez', 'Plant Manager'), ('Barbara Lopez', 'Operator'),
('Thomas Gonzalez', 'Quality Inspector');

-- 7. POPULATE CONTROL FACT ELEMENTS (QUALITY AUDITS)

INSERT INTO QUALITYCHECKS (ORIGINALQUALITYCHECKID, PRODUCTIONORDERID, INSPECTORID, CHECKTIMESTAMP, RESULT)
SELECT 
    D.QualityCheckID, P.PRODUCTIONID, E.EMPLOYEEID, 
    TRY_CONVERT(DATETIME, D.CheckTimestamp, 105), D.Result 
FROM DUMMY AS D
INNER JOIN PRODUCTIONORDERS AS P ON D.ProductionOrderID = P.PRODUCTIONCODE 
    AND D.ScheduledStart = P.SCHEDULEDSTARTDATE AND D.ScheduledEnd = P.SCHEDULEENDDATE 
    AND D.QuantityToProduce = P.QUANTITYTOPRODUCE AND D.ComponentToProduce = P.COMPONENTTOPRODUCE 
INNER JOIN EMPLOYEES AS E ON E.FULLNAME = D.InspectorName 
WHERE D.QualityCheckID IS NOT NULL;

-- 8. INITIALIZE POST-MIGRATION HISTORICAL REMAINING VALUES

UPDATE MI
SET MI.REMAINING_QUANTITY = MI.INITIAL_QUANTITY - ISNULL(P.QUANTITY_USED, 0)
FROM MATERIALINVENTORY AS MI
LEFT JOIN PRODUCTIONMATERIALUSAGE AS P ON P.BATCHID = MI.BATCHID AND P.MATERIALID = MI.MATERIALID;

UPDATE MATERIALINVENTORY
SET REMAINING_QUANTITY = INITIAL_QUANTITY WHERE REMAINING_QUANTITY IS NULL;
