-- creating  tables
--supplier [supplier id, supplier code, supplier name]

CREATE TABLE SUPPLIERS(
SUPPLIERID INT PRIMARY KEY IDENTITY(1,1),
SUPPLIERCODE NVARCHAR(50) NOT NULL UNIQUE,
SUPPLIERNAME NVARCHAR(50) NOT NULL
)

SELECT * FROM SUPPLIERS

--CUSTOMERS TABLE 
CREATE TABLE  CUSTOMERS(
CUSTOMERID INT PRIMARY KEY IDENTITY(1,1),
CUSTOMERCODE NVARCHAR(50) NOT NULL UNIQUE,
CUSTOMERNAME NVARCHAR(100) NOT NULL
)

SELECT * FROM CUSTOMERS

--RAW MATERIAL
CREATE TABLE RAWMATERIALS(
MATERIALID INT PRIMARY KEY IDENTITY(1,1),
MATERIALNAME NVARCHAR(100) NOT NULL,
MATERIALGRADE NVARCHAR(50) NULL,
CONSTRAINT UNIQUE_MATERIAL UNIQUE(MATERIALNAME,MATERIALGRADE)
)

SELECT * FROM RAWMATERIALS

-- MACHINE TABLE
CREATE TABLE MACHINES(
MACHINEID INT PRIMARY KEY IDENTITY(1,1),
MACHINECODE NVARCHAR(50) NOT NULL UNIQUE,
MACHINENAME NVARCHAR(50) NOT NULL,
MACHINETYPE NVARCHAR(50) NULL,
PLANTID NVARCHAR(10) NOT NULL,
LASTMAINTAINCEDATE DATE NULL
)

SELECT * FROM MACHINES

-- PRODUCTION ORDERS
CREATE TABLE PRODUCTIONORDERS(
PRODUCTIONID INT PRIMARY KEY IDENTITY(1,1),
PRODUCTIONCODE NVARCHAR(20) NOT NULL UNIQUE,
CUSTOMERID INT NOT NULL,
COMPONENTTOPRODUCE NVARCHAR(200) NOT NULL,
QUANTITYTOPRODUCE INT NOT NULL,
ORDERDATE DATETIME NOT NULL,
SCHEDULEDSTARTDATE DATETIME NOT NULL,
SCHEDULEENDDATE DATETIME NOT NULL,
[STATUS] NVARCHAR (50) NOT NULL,
ASSIGNEDMACHINEID INT NOT NULL,
PLANTID INT NOT NULL,

FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID),
FOREIGN KEY (ASSIGNEDMACHINEID) REFERENCES MACHINES(MACHINEID),
CONSTRAINT CHK_PRODUCTION_STATUS CHECK( [STATUS] IN ('Scheduled','In Progress','Complete','On Hold', 'Cancelled', 'Rework Required','Quoted'
,'Pending Materials','Rework Completed')),
CONSTRAINT CHK_ORDERDATES CHECK (SCHEDULEDSTARTDATE>=ORDERDATE),
CONSTRAINT CHK_SCHEDULESEQUENCE CHECK (SCHEDULEENDDATE >= SCHEDULEDSTARTDATE)

)

--- MATERIAL INVENTORY
CREATE TABLE MATERIALINVENTORY(
BATCHID INT PRIMARY KEY IDENTITY (1,1),
ORIGINALBATCHID NVARCHAR(50) UNIQUE,
MATERIALID INT NOT NULL,
SUPPLIERID INT NOT NULL,
RECEIVED_DATE DATE NOT NULL,
INITIAL_QUANTITY DECIMAL (10,2) NOT NULL,
REMAINING_QUANTITY DECIMAL (10,2) NOT NULL,
UNIT NVARCHAR(10) NOT NULL,

FOREIGN KEY (MATERIALID) REFERENCES RAWMATERIALS(MATERIALID),
FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIERS(SUPPLIERID)

)

SELECT * FROM MATERIALINVENTORY

--- PRODUCTION MATERIAL USAGES
CREATE TABLE PRODUCTIONMATERIALUSAGE(
USAGEID INT PRIMARY KEY IDENTITY (1,1),
PRODUCTIONORDERID INT NOT NULL,
BATCHID INT NOT NULL,
QUANTITY_USED DECIMAL(10,2) NOT NULL,

FOREIGN KEY (PRODUCTIONORDERID) REFERENCES PRODUCTIONORDERS(PRODUCTIONID),
FOREIGN KEY (BATCHID) REFERENCES MATERIALINVENTORY (BATCHID)

)

---EMPLOYEES
CREATE TABLE EMPLOYEES(
EMPLOYEEID INT PRIMARY KEY IDENTITY(1,1),
FULLNAME NVARCHAR(100) NOT NULL,
[ROLE] NVARCHAR(50) NOT NULL
)
SELECT * FROM EMPLOYEES

---QUALITY CHECKS
CREATE TABLE QUALITYCHECKS(
QUALITYCHECKID INT PRIMARY KEY IDENTITY(1,1),
ORIGINALQUALITYCHECKID NVARCHAR(50),
PRODUCTIONORDERID INT NOT NULL,
INSPECTORID INT NOT NULL,
CHECKTIMESTAMP DATETIME NOT NULL,
RESULT NVARCHAR(10),

FOREIGN KEY (PRODUCTIONORDERID) REFERENCES PRODUCTIONORDERS(PRODUCTIONID),
FOREIGN KEY (INSPECTORID) REFERENCES EMPLOYEES(EMPLOYEEID)
)

-----------------MIGRATION OF DATA FROM MAIN DATASOURCE TO DATABSE-----------------------------------------
SELECT * FROM ABC_10000

SELECT * FROM SUPPLIERS

ALTER TABLE SUPPLIERS
DROP COLUMN SUPPLIERCODE

ALTER TABLE SUPPLIERS 
DROP UQ__SUPPLIER__114532B94A3BE942


SELECT DISTINCT
    CASE
    WHEN SUPPLIERNAME LIKE '%PlasticPro%' then 'PlasticPro Inc.'
    WHEN SUPPLIERNAME LIKE 'Steel Corp%' then 'SteelCorp'
    WHEN SUPPLIERNAME LIKE 'Copper Co%' then 'CopperCo'
    WHEN SUPPLIERNAME LIKE 'Alu Works%' then 'AluWorks'
    WHEN SUPPLIERNAME LIKE '%GlobalMetals%' then 'Global Metals'
    else suppliername
    end
from ABC_10000 where SupplierName is not null

--- INSERT INTO SUPPLIER TABLE 
INSERT INTO SUPPLIERS(SUPPLIERNAME)
SELECT DISTINCT
    CASE
    WHEN SUPPLIERNAME LIKE '%PlasticPro%' then 'PlasticPro Inc.'
    WHEN SUPPLIERNAME LIKE 'Steel Corp%' then 'SteelCorp'
    WHEN SUPPLIERNAME LIKE 'Copper Co%' then 'CopperCo'
    WHEN SUPPLIERNAME LIKE 'Alu Works%' then 'AluWorks'
    WHEN SUPPLIERNAME LIKE '%GlobalMetals%' then 'Global Metals'
    else suppliername
    end
from ABC_10000 where SupplierName is not null

SELECT * FROM SUPPLIERS

--- INSERTION VALUE IN CUSTOMER TABLE

SELECT * FROM CUSTOMERS

SELECT DISTINCT CUSTOMERORDERID FROM ABC_10000
SELECT DISTINCT CUSTOMERNAME FROM ABC_10000

SELECT DISTINCT CUSTOMERORDERID,CUSTOMERNAME FROM ABC_10000

--- DROPING OF COLUMN CUSTOMERCODE FROM CUSTOMER TABLE
ALTER TABLE CUSTOMERS
DROP COLUMN CUSTOMERCODE

ALTER TABLE CUSTOMERS
DROP UQ__CUSTOMER__39788EB0AC2C1800

SELECT DISTINCT CUSTOMERNAME FROM ABC_10000

---INSERTION 
INSERT INTO CUSTOMERS(CUSTOMERNAME)
SELECT DISTINCT CUSTOMERNAME FROM ABC_10000

SELECT * FROM CUSTOMERS

--- RAW MATERIAL TABLE
SELECT * FROM RAWMATERIALS
SELECT * FROM ABC_10000

SELECT DISTINCT MATERIALNAME FROM ABC_10000
SELECT DISTINCT MATERIALGRADE FROM ABC_10000

SELECT DISTINCT MATERIALNAME,MATERIALGRADE FROM ABC_10000

---INSERT INTO RAW MATERIAL 
INSERT INTO RAWMATERIALS(MATERIALNAME,MATERIALGRADE)
SELECT DISTINCT MATERIALNAME,MATERIALGRADE FROM ABC_10000

SELECT * FROM RAWMATERIALS


--- MACHINES TABLE 
SELECT *  FROM MACHINES
SELECT * FROM ABC_10000

---MACHINE CODE 
SELECT DISTINCT MACHINEID,MACHINENAME FROM ABC_10000

ALTER TABLE MACHINES
DROP COLUMN MACHINECODE

ALTER TABLE MACHINES
DROP UQ__MACHINES__3EF2FB62DC578FDA




--DISTINCT MACHINE NAME
SELECT DISTINCT TRIM(REPLACE(REPLACE(MACHINENAME,'P1-',''),'P2-','')) FROM ABC_10000

---MACHINE TYPE
SELECT DISTINCT TRIM(MACHINETYPE) FROM ABC_10000

---PLANT ID 
SELECT DISTINCT LEFT(MACHINENAME,2) FROM ABC_10000

---LAST MAINTAINCE DATE
INSERT INTO MACHINES(MACHINENAME,MACHINETYPE,PLANTID,LASTMAINTAINCEDATE)
SELECT DISTINCT TRIM(REPLACE(REPLACE(MACHINENAME,'P1-',''),'P2-','')),TRIM(MACHINETYPE),LEFT(MACHINENAME,2),
MAX(LASTMAINTENANCEDATE) FROM ABC_10000
GROUP BY TRIM(REPLACE(REPLACE(MACHINENAME,'P1-',''),'P2-','')),TRIM(MACHINETYPE),LEFT(MACHINENAME,2)


--- CAST AND CONVERT [MM-DD-YY] NOW USE TRY_CONVERT 
INSERT INTO MACHINES(MACHINENAME,MACHINETYPE,PLANTID,LASTMAINTAINCEDATE)
SELECT DISTINCT TRIM(REPLACE(REPLACE(MACHINENAME,'P1-',''),'P2-','')),TRIM(MACHINETYPE),LEFT(MACHINENAME,2),
MAX (TRY_CONVERT(DATE,LASTMAINTENANCEDATE)) FROM ABC_10000
GROUP BY TRIM(REPLACE(REPLACE(MACHINENAME,'P1-',''),'P2-','')),TRIM(MACHINETYPE),LEFT(MACHINENAME,2)

SELECT * FROM MACHINES

--- MATERIAL INVENTORY
SELECT * FROM MATERIALINVENTORY

--ORIGINAL BATCHID
SELECT DISTINCT RAWMATERIALBATCHID FROM ABC_10000
SELECT DISTINCT LEFT(RAWMATERIALBATCHID,7) FROM ABC_10000

--MATERIAL ID
SELECT * FROM RAWMATERIALS

--- SUPPLIER ID
SELECT * FROM SUPPLIERS

--- RECEIVED DATE
SELECT RECEIVEDATE FROM ABC_10000--CHANGE DATA TYPE,AND MAKE DATA CONSISTENCE 
SELECT RECEIVEDATE,TRY_CONVERT(DATE,RECEIVEDATE,105) from ABC_10000

---INITIAL QUANTITY
SELECT INITIALQUANTITY FROM ABC_10000
SELECT CAST(INITIALQUANTITY AS FLOAT) FROM ABC_10000--   THROWNG AN ERROR

SELECT INITIALQUANTITY FROM ABC_10000 WHERE InitialQuantity LIKE '%[^0-9.]%'

--CLEANING [, $ SCIENTIFIC,SPACE]
SELECT INITIALQUANTITY,CAST(CAST( REPLACE(REPLACE(REPLACE(INITIALQUANTITY,'$',''),',',''),' ','')AS  FLOAT) AS DECIMAL(10,2)) FROM ABC_10000

---CONSTRIANTS

ALTER TABLE MATERIALINVENTORY
ADD CONSTRAINT CHK_UNIT CHECK (UNIT IN ('KG','M','PCS','FT','SQ_FT','LBS'))


---UNIT
SELECT DISTINCT UNIT FROM ABC_10000
SELECT DISTINCT STANDARDUNIT FROM
(
SELECT UNIT,
    CASE
    WHEN UPPER(TRIM(UNIT)) IN ('KG','KILOGRAM','KGS') THEN 'KG'
    WHEN UPPER(TRIM(UNIT)) IN ('M','METERS','METER') THEN 'M'
    WHEN UPPER(TRIM(UNIT)) IN ('PCS','PIECES') THEN 'PCS'
    WHEN UPPER(TRIM(UNIT)) IN ('FT','FEET') THEN 'FT'
    WHEN UPPER(TRIM(UNIT)) IN ('SQ FT','SQUQRE FEET') THEN 'SQ_FT'
    WHEN UPPER(TRIM(UNIT)) = 'LBS' THEN 'LBS'
    ELSE NULL
    END AS STANDARDUNIT
FROM ABC_10000
)K

--- COMBINE ALL
--COMMON COLUMN
--- 70% INFO ABC,15%-RAWMATERIAL,15- SUPPLIER

WITH T AS
( 
  SELECT LEFT(RAWMATERIALBATCHID,7) AS RAWMATERIALBATCHID,
  TRY_CONVERT(DATE,RECEIVEDATE,105) AS RECEIVEDDATE,
  CAST(CAST( REPLACE(REPLACE(REPLACE(INITIALQUANTITY,'$',''),',',''),' ','')AS  FLOAT) AS DECIMAL(10,2)) AS INITIAL_QUANTITY,
    CASE
    WHEN UPPER(TRIM(UNIT)) IN ('KG','KILOGRAM','KGS') THEN 'KG'
    WHEN UPPER(TRIM(UNIT)) IN ('M','METERS','METER') THEN 'M'
    WHEN UPPER(TRIM(UNIT)) IN ('PCS','PIECES') THEN 'PCS'
    WHEN UPPER(TRIM(UNIT)) IN ('FT','FEET') THEN 'FT'
    WHEN UPPER(TRIM(UNIT)) IN ('SQ FT','SQUQRE FEET') THEN 'SQ_FT'
    WHEN UPPER(TRIM(UNIT)) = 'LBS' THEN 'LBS'
    ELSE NULL
    END AS STANDARDUNIT
FROM DUMMY
)   
SELECT * FROM T


SELECT * INTO DUMMY FROM ABC_10000
SELECT * FROM DUMMY

UPDATE DUMMY
SET SUPPLIERNAME=
LTRIM(RTRIM(
    CASE
    WHEN SUPPLIERNAME LIKE '%PlasticPro%' then 'PlasticPro Inc.'
    WHEN SUPPLIERNAME LIKE 'Steel Corp%' then 'SteelCorp'
    WHEN SUPPLIERNAME LIKE 'Copper Co%' then 'CopperCo'
    WHEN SUPPLIERNAME LIKE 'Alu Works%' then 'AluWorks'
    WHEN SUPPLIERNAME LIKE '%GlobalMetals%' then 'Global Metals'
    else suppliername
    end ))
SELECT DISTINCT SUPPLIERNAME FROM ABC_10000
SELECT DISTINCT SUPPLIERNAME FROM DUMMY WHERE SUPPLIERNAME IS NOT NULL

--- RAW MATERIAL TABLE
---ABC[T]---SUPPLIER (SUPPLIER NAME)
---ABC[T]--- RAW MATERIAL TABLE (MATERIALNAME , MATERIALGRADE)


---LETS JOIN
WITH T AS
( 
  SELECT LEFT(RAWMATERIALBATCHID,7) AS RAWMATERIALBATCHID,
  TRY_CONVERT(DATE,RECEIVEDATE,105) AS RECEIVEDDATE,
  CAST(CAST( REPLACE(REPLACE(REPLACE(INITIALQUANTITY,'$',''),',',''),' ','')AS  FLOAT) AS DECIMAL(10,2)) AS INITIAL_QUANTITY,
    CASE
    WHEN UPPER(TRIM(UNIT)) IN ('KG','KILOGRAM','KGS') THEN 'KG'
    WHEN UPPER(TRIM(UNIT)) IN ('M','METERS','METER') THEN 'M'
    WHEN UPPER(TRIM(UNIT)) IN ('PCS','PIECES') THEN 'PCS'
    WHEN UPPER(TRIM(UNIT)) IN ('FT','FEET') THEN 'FT'
    WHEN UPPER(TRIM(UNIT)) IN ('SQ FT','SQUQRE FEET') THEN 'SQ_FT'
    WHEN UPPER(TRIM(UNIT)) = 'LBS' THEN 'LBS'
    ELSE NULL
    END AS STANDARDUNIT, SUPPLIERNAME,MATERIALNAME,MATERIALGRADE
FROM DUMMY
)   
SELECT T.RAWMATERIALBATCHID,M.MATERIALID,S.SUPPLIERID,T.RECEIVEDDATE,INITIAL_QUANTITY,T.STANDARDUNIT FROM T INNER JOIN
SUPPLIERS AS S ON S.SUPPLIERNAME=T.SUPPLIERNAME
INNER JOIN RAWMATERIALS AS M 
ON M.MATERIALGRADE=T.MATERIALGRADE AND M.MATERIALNAME=T.MATERIALNAME

---INSERTING DATA IN MATERIAL INVENTORY TABLE
WITH T AS
( 
  SELECT LEFT(RAWMATERIALBATCHID,7) AS RAWMATERIALBATCHID,
  TRY_CONVERT(DATE,RECEIVEDATE,105) AS RECEIVEDDATE,
  CAST(CAST( REPLACE(REPLACE(REPLACE(INITIALQUANTITY,'$',''),',',''),' ','')AS  FLOAT) AS DECIMAL(10,2)) AS INITIAL_QUANTITY,
    CASE
    WHEN UPPER(TRIM(UNIT)) IN ('KG','KILOGRAM','KGS') THEN 'KG'
    WHEN UPPER(TRIM(UNIT)) IN ('M','METERS','METER') THEN 'M'
    WHEN UPPER(TRIM(UNIT)) IN ('PCS','PIECES') THEN 'PCS'
    WHEN UPPER(TRIM(UNIT)) IN ('FT','FEET') THEN 'FT'
    WHEN UPPER(TRIM(UNIT)) IN ('SQ FT','SQUQRE FEET') THEN 'SQ_FT'
    WHEN UPPER(TRIM(UNIT)) = 'LBS' THEN 'LBS'
    ELSE NULL
    END AS STANDARDUNIT, SUPPLIERNAME,MATERIALNAME,MATERIALGRADE
FROM DUMMY
)
INSERT INTO MATERIALINVENTORY(ORIGINALBATCHID, MATERIALID,SUPPLIERID,RECEIVED_DATE, INITIAL_QUANTITY, UNIT)
SELECT T.RAWMATERIALBATCHID,M.MATERIALID,S.SUPPLIERID,T.RECEIVEDDATE,INITIAL_QUANTITY,T.STANDARDUNIT FROM T INNER JOIN
SUPPLIERS AS S ON S.SUPPLIERNAME=T.SUPPLIERNAME
INNER JOIN RAWMATERIALS AS M 
ON M.MATERIALGRADE=T.MATERIALGRADE AND M.MATERIALNAME=T.MATERIALNAME

---REMOVE COLUMN REMAINING QUANTITY
ALTER TABLE MATERIALINVENTORY
ALTER COLUMN REMAINING_QUANTITY DECIMAL(9,2) NULL


ALTER TABLE MATERIALINVENTORY
DROP UQ__MATERIAL__598D89C1A1EB0131

SELECT * FROM MATERIALINVENTORY

DELETE FROM MATERIALINVENTORY
DBCC CHECKIDENT('MATERIALINVENTORY', RESEED,0)

------------------------------------------------------------- PRODUCTION ORDERS--------
SELECT * FROM PRODUCTIONORDERS
---60-- DATA IS FROM ABC 
--10 CUSTOMER TABLE --CUSTOMERID
--30 MACHINE TABLE -- MACHINEID AND PLANTID 


---PRODUCTION CODE
SELECT DISTINCT PRODUCTIONORDERID FROM ABC_10000 
SELECT DISTINCT REPLACE(REPLACE(PRODUCTIONORDERID,'/','-'),'_','-') FROM ABC_10000

SELECT DISTINCT RIGHT(REPLACE(REPLACE(PRODUCTIONORDERID,'/','-'),'_','-'),4) FROM ABC_10000

---CUSTOMERID
SELECT * FROM CUSTOMERS
SELECT * FROM DUMMY AS D
INNER JOIN
CUSTOMERS AS C ON C.CUSTOMERNAME=D.CustomerName


--- COMPONENT TO PRODUCE 
SELECT COMPONENTTOPRODUCE FROM ABC_10000

---QUANITY TO PRODUCE
SELECT CAST(CEILING(QUANTITYTOPRODUCE)  AS INT) FROM ABC_10000

---ORDER DATE
SELECT ORDERDATE , TRY_CONVERT(DATETIME,ORDERDATE,105) FROM ABC_10000
SELECT ORDERDATE , TRY_CONVERT(DATETIME,ORDERDATE,110) FROM ABC_10000
SELECT ORDERDATE, COALESCE(
         TRY_CONVERT(DATETIME,ORDERDATE,105),
         TRY_CONVERT(DATETIME,ORDERDATE,110)) AS CONVERTEDDATE
         FROM ABC_10000

--- SCHEDULE START DATE AND SCHEDULE END DATE 
SELECT SCHEDULEDSTART , TRY_CONVERT(DATETIME,SCHEDULEDSTART,105),SCHEDULEDEND,TRY_CONVERT(DATETIME,SCHEDULEDEND,105) FROM ABC_10000

---STATUS
SELECT DISTINCT STATUS FROM ABC_10000

--- MACHINEID AND PLANTID
SELECT * FROM MACHINES

UPDATE DUMMY
SET MACHINENAME=TRIM(REPLACE(REPLACE(MACHINENAME,'P1-',''),'P2-','')),
MACHINETYPE=TRIM(MACHINETYPE)

SELECT * FROM DUMMY

SELECT* FROM MACHINES AS M
INNER JOIN  DUMMY AS D
 ON M.MACHINENAME=D.MachineName AND M.MACHINETYPE=D.MachineType

---DATA SELECTION
SELECT 
    RIGHT(REPLACE(REPLACE(D.PRODUCTIONORDERID, '/', '-'), '_', '-'), 4) AS ORIGINALPRODUCTID,
    C.CUSTOMERID,
    D.COMPONENTTOPRODUCE,
    CAST(CEILING(D.QUANTITYTOPRODUCE) AS INT) AS QUANTITY_TO_PRODUCE,
    COALESCE(
        TRY_CONVERT(DATETIME, ORDERDATE, 105),
        TRY_CONVERT(DATETIME, ORDERDATE, 110)
    ) AS ORDERDATE,
    TRY_CONVERT(DATETIME, SCHEDULEDSTART, 105) AS SCHEDULEDSTART,
    TRY_CONVERT(DATETIME, SCHEDULEDEND, 105) AS SCHEDULEDEND,
    D.STATUS,
    M.MACHINEID,
    M.PLANTID
FROM DUMMY AS D
INNER JOIN CUSTOMERS AS C ON C.CUSTOMERNAME = D.CUSTOMERNAME
INNER JOIN MACHINES AS M ON M.MACHINENAME = D.MACHINENAME AND M.MACHINETYPE = D.MACHINETYPE

---INSERTION
INSERT INTO PRODUCTIONORDERS(PRODUCTIONCODE,CUSTOMERID,COMPONENTTOPRODUCE,QUANTITYTOPRODUCE,ORDERDATE,SCHEDULEDSTARTDATE,SCHEDULEENDDATE,[STATUS],
ASSIGNEDMACHINEID,PLANTID)
SELECT 
    RIGHT(REPLACE(REPLACE(D.PRODUCTIONORDERID, '/', '-'), '_', '-'), 4) AS ORIGINALPRODUCTID,
    C.CUSTOMERID,
    D.COMPONENTTOPRODUCE,
    CAST(CEILING(D.QUANTITYTOPRODUCE) AS INT) AS QUANTITY_TO_PRODUCE,
    COALESCE(
        TRY_CONVERT(DATETIME, ORDERDATE, 105),
        TRY_CONVERT(DATETIME, ORDERDATE, 110)
    ) AS ORDERDATE,
    TRY_CONVERT(DATETIME, SCHEDULEDSTART, 105) AS SCHEDULEDSTART,
    TRY_CONVERT(DATETIME, SCHEDULEDEND, 105) AS SCHEDULEDEND,
    D.STATUS,
    M.MACHINEID,
    M.PLANTID
FROM DUMMY AS D
INNER JOIN CUSTOMERS AS C ON C.CUSTOMERNAME = D.CUSTOMERNAME
INNER JOIN MACHINES AS M ON M.MACHINENAME = D.MACHINENAME AND M.MACHINETYPE = D.MACHINETYPE
WHERE TRY_CONVERT(DATETIME, SCHEDULEDEND, 105)>=TRY_CONVERT(DATETIME, SCHEDULEDSTART, 105) AND TRY_CONVERT(DATETIME, SCHEDULEDSTART, 105)>=COALESCE(
        TRY_CONVERT(DATETIME, ORDERDATE, 105),
        TRY_CONVERT(DATETIME, ORDERDATE, 110))

---EDITING
ALTER TABLE PRODUCTIONORDERS
ALTER COLUMN PLANTID NVARCHAR(3)

ALTER TABLE PRODUCTIONORDERS
DROP CHK_PRODUCTION_STATUS

ALTER TABLE PRODUCTIONORDERS
DROP UQ__PRODUCTI__A52DAC976634871D


ALTER TABLE PRODUCTIONORDERS
ADD CONSTRAINT CHK_PRODUCTION_STATUS CHECK( [STATUS] IN ('Scheduled','In Progress','Completed','On Hold', 'Cancelled', 'Rework Required','Quoted'
,'Pending Materials','Rework Complete'))

SELECT * FROM PRODUCTIONORDERS
--- PRODUCTION CODE SHOULD START FROM 1
DELETE FROM PRODUCTIONORDERS
DBCC CHECKIDENT('PRODUCTIONORDERS', RESEED,0)

--------------PRODUCTION MATERIAL USAGES---------------------
SELECT * FROM PRODUCTIONMATERIALUSAGE

---ADD COLUMN MATERIAL ID
ALTER TABLE PRODUCTIONMATERIALUSAGE
ADD MATERIALID INT

ALTER TABLE PRODUCTIONMATERIALUSAGE
ADD CONSTRAINT FK_PRODUCTION FOREIGN KEY (MATERIALID) REFERENCES RAWMATERIALS(MATERIALID)

---col2--production order
---col3--material inventory
---col4--dummy
---col5--material inventory

UPDATE DUMMY
SET PRODUCTIONORDERID=RIGHT(REPLACE(REPLACE(PRODUCTIONORDERID, '/', '-'), '_', '-'), 4),
SCHEDULEDSTART=TRY_CONVERT(DATETIME, SCHEDULEDSTART, 105),
SCHEDULEDEND=TRY_CONVERT(DATETIME, SCHEDULEDEND, 105),
QUANTITYTOPRODUCE=CAST(CEILING(QuantityToProduce) AS INT)

SELECT * FROM DUMMY AS D
INNER JOIN PRODUCTIONORDERS AS P
ON D.ProductionOrderID=P.PRODUCTIONCODE AND D.ScheduledStart=P.SCHEDULEDSTARTDATE
AND D.ScheduledEnd=P.SCHEDULEENDDATE AND D.QuantityToProduce=P.QUANTITYTOPRODUCE
AND D.ComponentToProduce=P.COMPONENTTOPRODUCE

---BATCH ID
SELECT DISTINCT ORIGINALBATCHID FROM MATERIALINVENTORY
SELECT DISTINCT MATERIALUSEDBATCHID FROM DUMMY


SELECT DISTINCT ORIGINALBATCHID FROM MATERIALINVENTORY
WHERE ORIGINALBATCHID IN
(
SELECT DISTINCT MATERIALUSEDBATCHID FROM DUMMY
)
---JOIN AND INSERTION---
INSERT INTO PRODUCTIONMATERIALUSAGE(PRODUCTIONORDERID,BATCHID,QUANTITY_USED,MATERIALID)
SELECT P.PRODUCTIONID,M.BATCHID,D.QuantityUsed,M.MATERIALID FROM DUMMY AS D
INNER JOIN PRODUCTIONORDERS AS P
ON D.ProductionOrderID=P.PRODUCTIONCODE AND D.ScheduledStart=P.SCHEDULEDSTARTDATE
AND D.ScheduledEnd=P.SCHEDULEENDDATE AND D.QuantityToProduce=P.QUANTITYTOPRODUCE
AND D.ComponentToProduce=P.COMPONENTTOPRODUCE
INNER JOIN  MATERIALINVENTORY AS M ON M.ORIGINALBATCHID=D.MaterialUsedBatchID

---EDITING 
ALTER TABLE PRODUCTIONMATERIALUSAGE
ALTER COLUMN QUANTITY_USED DECIMAL(10,2) NULL

SELECT * FROM PRODUCTIONMATERIALUSAGE

DELETE FROM PRODUCTIONMATERIALUSAGE
DBCC CHECKIDENT('PRODUCTIONMATERIALUSAGE', RESEED,0)

SELECT * FROM MATERIALINVENTORY

UPDATE M
SET  M.REMAINING_QUANTITY=M.INITIAL_QUANTITY- P.QUANTITY_USED
FROM PRODUCTIONMATERIALUSAGE AS P
INNER JOIN MATERIALINVENTORY AS M
ON P.BATCHID=M.BATCHID AND P.MATERIALID=M.MATERIALID


SELECT * FROM MATERIALINVENTORY
UPDATE MATERIALINVENTORY
SET REMAINING_QUANTITY=INITIAL_QUANTITY WHERE REMAINING_QUANTITY IS NULL

-----CREATE A TABLE
CREATE TABLE EMPLOYEES_RAW(
FULLNAME NVARCHAR(50),
ROLE NVARCHAR(50)
)
SELECT * FROM EMPLOYEES_RAW

INSERT INTO EMPLOYEES_RAW (FULLNAME, ROLE) VALUES
('John Doe', 'Quality Inspector'),
('Jane Smith', 'Quality Inspector'),
('Peter Jones', 'Plant Manager'),
('Mary Williams', 'Quality Inspector'),
('David Brown', 'Operator'),
('Susan Miller', 'Quality Inspector'),
('Robert Johnson', 'Plant Manager'),
('Karen White', 'Operator'),
('Michael Lee', 'Quality Inspector'),
('Patricia Garcia', 'Operator'),
('James Rodriguez', 'Operator'),
('Linda Martinez', 'Quality Inspector'),
('Charles Hernandez', 'Plant Manager'),
('Barbara Lopez', 'Operator'),
('Thomas Gonzalez', 'Quality Inspector')

SELECT * FROM EMPLOYEES

INSERT INTO EMPLOYEES(FULLNAME, ROLE)
SELECT * FROM EMPLOYEES_RAW
         

-----------------------------------QUALITY CHECK----------
SELECT * FROM QUALITYCHECKS

--COL2- DUMMY,COL3-PRODUCTIONORDERS,COL4-EMPLOYEES,COL5,6-DUMMY

--COL2
SELECT QUALITYCHECKID FROM DUMMY WHERE QualityCheckID IS NULL

---COL3 JOIN PRODUCTIONORDERS TABLE WITH DUMMY 
SELECT * FROM DUMMY AS D
INNER JOIN PRODUCTIONORDERS AS P
ON D.ProductionOrderID=P.PRODUCTIONCODE AND D.ScheduledStart=P.SCHEDULEDSTARTDATE
AND D.ScheduledEnd=P.SCHEDULEENDDATE AND D.QuantityToProduce=P.QUANTITYTOPRODUCE
AND D.ComponentToProduce=P.COMPONENTTOPRODUCE WHERE QualityCheckID IS NOT NULL

---COL4-- JOIN ABOVE TABLE WITH EMPLOYEE
SELECT * FROM DUMMY AS D
INNER JOIN PRODUCTIONORDERS AS P
ON D.ProductionOrderID=P.PRODUCTIONCODE AND D.ScheduledStart=P.SCHEDULEDSTARTDATE
AND D.ScheduledEnd=P.SCHEDULEENDDATE AND D.QuantityToProduce=P.QUANTITYTOPRODUCE
AND D.ComponentToProduce=P.COMPONENTTOPRODUCE INNER JOIN EMPLOYEES AS E ON E.FULLNAME=D.InspectorName WHERE QualityCheckID IS NOT NULL

---FILTER AND INSERT
INSERT INTO QUALITYCHECKS(ORIGINALQUALITYCHECKID,PRODUCTIONORDERID,INSPECTORID,CHECKTIMESTAMP,RESULT)
SELECT D.QualityCheckID,P.PRODUCTIONID,E.EMPLOYEEID,TRY_CONVERT(DATETIME, D.CheckTimestamp,105),D.Result FROM DUMMY AS D
INNER JOIN PRODUCTIONORDERS AS P
ON D.ProductionOrderID=P.PRODUCTIONCODE AND D.ScheduledStart=P.SCHEDULEDSTARTDATE
AND D.ScheduledEnd=P.SCHEDULEENDDATE AND D.QuantityToProduce=P.QUANTITYTOPRODUCE
AND D.ComponentToProduce=P.COMPONENTTOPRODUCE INNER JOIN EMPLOYEES AS E ON E.FULLNAME=D.InspectorName WHERE QualityCheckID IS NOT NULL


---EDITING
ALTER TABLE QUALITYCHECKS
ALTER COLUMN CHECKTIMESTAMP DATETIME NULL

SELECT * FROM QUALITYCHECKS

--------------------------------END----------------------

---SCENARIO-1
---QUALITY CHECK-FAILED

---SCENARIO-2
--PRODUCTION MATERIAL USAGE --TABLE --UPDATE ANY QUATITY ,OR INSERTED ANY NEW ROW,
---MATERIAL INVENTORY- REAMINING QUANTITY

---SCENARIO-3
--NEW PRODUCTION --INSERT OR UPATING SCHEDULE FOR ANY PRODUCTION --MACHINE THAT IS USED TO BE FREE OR NOT 

--SCENARIO-4
--MATERIAL INVENTORY TAABLE , I HAVE NO ALARMING SYSTEM




-------------------------------------------------
        ----------------------------------------------
                                                --SCENARIO-1: FAILED QUALITY CHECK, STATUS SHOULD BE REWROK REQUIRED

UPDATE PRODUCTIONORDERS
SET [STATUS]='REWORK REQUIRED'
WHERE 
PRODUCTIONID IN
(
SELECT PRODUCTIONORDERID FROM QUALITYCHECKS WHERE RESULT='FAILED'
)

SELECT * FROM PRODUCTIONORDERS
WHERE 
PRODUCTIONID IN
(
SELECT PRODUCTIONORDERID FROM QUALITYCHECKS WHERE RESULT='FAILED'
)

---production table 
-- quality check [result]
--in future result failed , look for production id and for that production id , update the status as rework required 
---trigger-- quality check -- after insert
CREATE TRIGGER UPDATEPRODUCTIONSTATUS_ONFAIL
ON QUALITYCHECKS
AFTER INSERT
AS 
BEGIN
    UPDATE P
    SET P.STATUS ='REWORK REQUIRED'
    FROM INSERTED AS I
    INNER JOIN PRODUCTIONORDERS AS P
    on i.PRODUCTIONORDERID=P.PRODUCTIONID
    WHERE I.RESULT='FAILED'

END

SELECT * FROM PRODUCTIONORDERS
SELECT * FROM QUALITYCHECKS

DROP TRIGGER TRG_PREVENTOVERLAPPINGSCHEDULES

INSERT INTO QUALITYCHECKS(ORIGINALQUALITYCHECKID,PRODUCTIONORDERID,INSPECTORID,CHECKTIMESTAMP,RESULT)
VALUES ('QC-283',1,1,NULL,'FAILED')

---SCENARIO:2
--ANY UPDATION IN MY PRODUCTION MATERIAL USED TABLE SHOULD MAKE RELATIVE CHANGES IN THE INVENTORY TABLE
-- ANY ROW INSERTED INTO PRODUCTION MATERIAL USAGE SHOULD SHOW RELATIVE CHANGES IN THE REMAINING QUANTITY COLUMN OF THE TABLE MATERIAL INVENTORY
--ANY UPDATION IN ALREADY EXISTING MATERIAL USAGE SHOULD SHOW RELATIVE CHANGES IN THE REMAINING QUANTITY COLUMN
-- IF QUANNTIY USED IS MORE THAN QUANTITY REMAINNIG IN INVENTORY TABLE DONT ALLOW ENTRY OF THAT ROW ,OR UPDATION OF THAT ROW

CREATE TRIGGER TRG_UPDATEMATERIALREMAINING
ON PRODUCTIONMATERIALUSAGE
AFTER INSERT ,UPDATE 
AS
BEGIN   ---UPDATE
        -- DELETE
        IF EXISTS(SELECT 1 FROM DELETED)
        BEGIN
            UPDATE MI
            SET MI.REMAINING_QUANTITY=MI.REMAINING_QUANTITY+D.QUANTITY_USED
            FROM  DELETED AS D INNER JOIN
            MATERIALINVENTORY AS MI 
            ON D.BATCHID=MI.BATCHID AND D.MATERIALID=MI.MATERIALID
          END


          ---INSERT
          UPDATE MI
          SET MI.REMAINING_QUANTITY=MI.REMAINING_QUANTITY-I.QUANTITY_USED
          FROM MATERIALINVENTORY AS MI 
          INNER JOIN INSERTED AS I
          ON I.BATCHID=MI.BATCHID AND I.MATERIALID=MI.MATERIALID

          ---
          IF EXISTS (SELECT 1
          FROM MATERIALINVENTORY AS MI 
          INNER JOIN INSERTED AS I
          ON I.BATCHID=MI.BATCHID AND I.MATERIALID=MI.MATERIALID
          WHERE MI.REMAINING_QUANTITY<0)
          BEGIN 
             RAISERROR('INSUFFICIENT MATERIAL',16,1)
             ROLLBACK TRANSACTION 
             RETURN
             END 
END
---TESTING 
SELECT * FROM MATERIALINVENTORY WHERE BATCHID=105
SELECT * FROM PRODUCTIONMATERIALUSAGE WHERE BATCHID=105

INSERT INTO PRODUCTIONMATERIALUSAGE(PRODUCTIONORDERID, BATCHID,QUANTITY_USED, MATERIALID)
VALUES (5,105,200,58)

update PRODUCTIONMATERIALUSAGE SET QUANTITY_USED=500 WHERE USAGEID=123479



---- SCENARIO:3------------AVOIDIDING MULTIPLE TO BE SCHEDULE AT SAME TIME FOR DIFFEERENT TASK  

CREATE TRIGGER TRG_CHECKMACHINESCHEDULE
ON PRODUCTIONORDERS 
AFTER INSERT ,UPDATE 
AS 
BEGIN
    IF EXISTS (
         SELECT 1
         FROM INSERTED AS I 
         JOIN PRODUCTIONORDERS AS P
         -- MUST BE FOR SAME MACHINE 
         ON I.ASSIGNEDMACHINEID=P.ASSIGNEDMACHINEID
         --MUST NOT BE EXACT SAME ORDER (HANDLES SELF UPDATES )
         AND I.PRODUCTIONID<>P.PRODUCTIONID
       WHERE 
           I.STATUS NOT IN ('COMPLETED','CANCELLED')


           --- THIS THIS THE OVERLAP LOGIC 
           --1 THE NW=E W ORDERS START IS BEFORE THE EXISTNG ORDER END 
           AND (I.SCHEDULEDSTARTDATE<P.SCHEDULEENDDATE)

           --2 AND THE NEW ORDER EBD IS AFTER EXISTING ORDERS START 
           AND I.SCHEDULEENDDATE>P.SCHEDULEDSTARTDATE

       )

       BEGIN 
       -- IF CONFLICT IS FOUND, RAISE AN ERROR AND CANCEL THE OPERATION 
       RAISERROR ('SCHEDULE CONFLICT : THE ASSIGNED MACHINE IS ALREADY OCCUPIED DURING THIS TIME PERIOSD ',16,1)
       ROLLBACK TRANSACTION ;
       RETURN;
END;
END;


---------------SCENARIO:4--------------
---MATRIAL INVENTORY TABLE KEEP AN ALARM ON MATERIAL QUANTITY BECOMES LESS THAN 500
--MATERIAL ORDER 

CREATE TABLE MATERIALLOWSTOCKLOG (
LOGINID INT PRIMARY KEY IDENTITY(1,1),
MATERIALID INT NOT NULL,
MATERIALNAME NVARCHAR(100),
MATERIALGRADE NVARCHAR (50),
ALERTTRIGGERQUANTITY DECIMAL (10,2),-- HOW MUCH WAS LEFT WHEN TRIGERED
QUANTITYORDEER DECIMAL (10,2),      -- THE NEW CALCUALTED COLUMN
ALERTDATE DATETIME DEFAULT GETDATE()
)

--TRIGGER MATERIAL INVENTORY 
-- AFTER INSERT OR UPDATE

CREATE TRIGGER TRG_LOWSTOCK
ON MATERIALINVENTORY 
AFTER INSERT ,UPDATE 
AS 
BEGIN 
     INSERT INTO MATERIALLOWSTOCKLOG(MATERIALID, MATERIALNAME,MATERIALGRADE, ALERTTRIGGERQUANTITY,QUANTITYORDEER)
     SELECT I.MATERIALID,M.MATERIALNAME,M.MATERIALGRADE,I.REMAINING_QUANTITY, (4000-I.REMAINING_QUANTITY) FROM INSERTED AS I
     INNER JOIN RAWMATERIALS AS M ON I.MATERIALID=M.MATERIALID
     WHERE I.REMAINING_QUANTITY<500



END

--- TESTING 
SELECT * FROM MATERIALLOWSTOCKLOG















